//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExampleTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class XoaND
    {
        public Nullable<int> Id { get; set; }
        public string namefile { get; set; }
        public string thoigian { get; set; }
        public Nullable<int> userId { get; set; }
        public string tag { get; set; }
    }
}
